export const SIZES = {
  SMALL: 'SMALL',
  MEDIUM: 'MEDIUM',
  LARGE: 'LARGE',
}

export const LIGHTS = {
  LOW_LIGHT: 'LOW LIGHT',
  DIRECT_LIGHT: 'DIRECT LIGHT',
  INDIRECT_LIGHT: 'INDIRECT LIGHT',
}

export const CARES = {
  EASY: 'EASY',
  MODERATE: 'MODERATE',
  ADVANCE: 'ADVANCE',
}

export const PLANT_TYPES = {
  SUCCULENTS_PLANTS: 'SUCCULENTS PLANTS',
  MEDICINE_PLANTS: 'MEDICINE PLANTS',
  TROPICAL_PLANTS: 'TROPICAL PLANTS',
  FLOWERING_PLANTS: 'FLOWERING PLANTS',
  RARE_PLANTS: 'RARE PLANTS',
  OUTDOOR_PLANTS: 'OUTDOOR PLANTS',
  HOUSE_PLANTS: 'HOUSE PLANTS',
  HANGING_PLANTS: 'HANGING PLANTS',
  FRUIT_PLANTS: 'FRUIT PLANTS',
  BONSAI_PLANTS: 'BONSAI PLANTS',
  FLOOR_PLANTS: 'FLOOR PLANTS',
  FARM_PLANTS: 'FARM PLANTS',
}

export const PLANT_GIFTS = {
  BIRTHDAY_COLLECTION: 'BIRTHDAY COLLECTION',
  FRIENDSHIP_DAY_GIFTS: 'FRIENDSHIP DAY GIFTS',
  CORPORATE_GIFTS: 'CORPORATE GIFTS',
  BACK_TO_SCHOOL_GIFTS: 'BACK TO SCHOOL GIFTS',
  SYMPATHY_PLANTS: 'SYMPATHY PLANTS',
  GIFTS_FOR_PARENTS: 'GIFTS FOR PARENTS',
  HOUSEWARMING_COLLECTION: 'HOUSEWARMING COLLECTION',
  GRANDPARENTS_DAY_GIFTS: 'GRANDPARENTS DAY GIFTS',
  THANK_YOU_COLLECTION: 'THANK YOU COLLECTION',
}

export const PLANT_LIFE_STYLES = {
  FENG_SHUI_PLANTS: 'FENG SHUI PLANTS',
  ZODIAC_PLANTS: 'ZODIAC PLANTS',
  AIR_PURIFYING_PLANTS: 'AIR PURIFYING PLANTS',
  PLANTS_FOR_BEGINNERS: 'PLANTS FOR BEGINNERS',
  FLOWERING_PLANTS: 'FLOWERING PLANTS',
  FRUIT_PLANTS: 'FRUIT PLANTS',
  FARM_PLANTS: 'FARM PLANTS',
}
