const payload = [
  {
    name: "Polyscias balfouriana",
    code: "A001",
    description: "plant Detail",
    imageUrl: "Polyscias_balfouriana.jpg",
    ProductSizes: [
      { name: "SMALL", price: 3 },
      { name: "MEDIUM", price: 5 },
      { name: "LARGE", price: 8 },
    ],
    ProductCares: [{ name: "ADVANCE" }, { name: "EASY" }, { name: "MODERATE" }],
    ProductLights: [
      { name: "DIRECT LIGHT" },
      { name: "INDIRECT LIGHT" },
      { name: "LOW LIGHT" },
    ],
    PlantTypes: [
      { name: "MEDICINE PLANTS" },
      { name: "SUCCULENTS PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FLOOR PLANTS" },
      { name: "BONSAI PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "HANGING PLANTS" },
      { name: "HOUSE PLANTS" },
      { name: "OUTDOOR PLANTS" },
      { name: "RARE PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "TROPICAL PLANTS" },
    ],
    PlantGifts: [
      { name: "BIRTHDAY COLLECTION" },
      { name: "BIRTHDAY COLLECTION" },
      { name: "FRIENDSHIP DAY GIFTS" },
      { name: "CORPORATE GIFTS" },
      { name: "BACK TO SCHOOL GIFTS" },
      { name: "SYMPATHY PLANTS" },
      { name: "GIFTS FOR PARENTS" },
      { name: "HOUSEWARMING COLLECTION" },
      { name: "GRANDPARENTS DAY GIFTS" },
      { name: "THANK YOU COLLECTION" },
    ],
    PlantLifeStyles: [
      { name: "FENG SHUI PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "PLANTS FOR BEGINNERS" },
      { name: "AIR PURIFYING PLANTS" },
      { name: "ZODIAC PLANTS" },
    ],
    ProductImages: [
      { name: "Polyscias_balfouriana1.jpg" },
      { name: "Polyscias_balfouriana2.jpg" },
      { name: "Polyscias_balfouriana3.jpg" },
      { name: "Polyscias_balfouriana4.jpg" },
      { name: "Polyscias_balfouriana5.jpg" },
    ],
  },
  {
    name: "Calathea roseopicta",
    code: "A002",
    description: "plant Detail",
    imageUrl: "Calathea_roseopicta.jpg",
    ProductSizes: [
      { name: "SMALL", price: 3 },
      { name: "MEDIUM", price: 5 },
      { name: "LARGE", price: 8 },
    ],
    ProductCares: [{ name: "ADVANCE" }, { name: "EASY" }, { name: "MODERATE" }],
    ProductLights: [
      { name: "DIRECT LIGHT" },
      { name: "INDIRECT LIGHT" },
      { name: "LOW LIGHT" },
    ],
    PlantTypes: [
      { name: "MEDICINE PLANTS" },
      { name: "SUCCULENTS PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FLOOR PLANTS" },
      { name: "BONSAI PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "HANGING PLANTS" },
      { name: "HOUSE PLANTS" },
      { name: "OUTDOOR PLANTS" },
      { name: "RARE PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "TROPICAL PLANTS" },
    ],
    PlantGifts: [
      { name: "BIRTHDAY COLLECTION" },
      { name: "BIRTHDAY COLLECTION" },
      { name: "FRIENDSHIP DAY GIFTS" },
      { name: "CORPORATE GIFTS" },
      { name: "BACK TO SCHOOL GIFTS" },
      { name: "SYMPATHY PLANTS" },
      { name: "GIFTS FOR PARENTS" },
      { name: "HOUSEWARMING COLLECTION" },
      { name: "GRANDPARENTS DAY GIFTS" },
      { name: "THANK YOU COLLECTION" },
    ],
    PlantLifeStyles: [
      { name: "FENG SHUI PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "PLANTS FOR BEGINNERS" },
      { name: "AIR PURIFYING PLANTS" },
      { name: "ZODIAC PLANTS" },
    ],
    ProductImages: [
      { name: "Calathea_roseopicta1.jpg" },
      { name: "Calathea_roseopicta2.jpg" },
      { name: "Calathea_roseopicta3.jpg" },
      { name: "Calathea_roseopicta4.jpg" },
      { name: "Calathea_roseopicta5.jpg" },
    ],
  },
  {
    name: "Gymnocalycium baldianum",
    code: "A002",
    description: "plant Detail",
    imageUrl: "Gymnocalycium_baldianum.jpg",
    ProductSizes: [
      { name: "SMALL", price: 3 },
      { name: "MEDIUM", price: 5 },
      { name: "LARGE", price: 8 },
    ],
    ProductCares: [{ name: "ADVANCE" }, { name: "EASY" }, { name: "MODERATE" }],
    ProductLights: [
      { name: "DIRECT LIGHT" },
      { name: "INDIRECT LIGHT" },
      { name: "LOW LIGHT" },
    ],
    PlantTypes: [
      { name: "MEDICINE PLANTS" },
      { name: "SUCCULENTS PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FLOOR PLANTS" },
      { name: "BONSAI PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "HANGING PLANTS" },
      { name: "HOUSE PLANTS" },
      { name: "OUTDOOR PLANTS" },
      { name: "RARE PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "TROPICAL PLANTS" },
    ],
    PlantGifts: [
      { name: "BIRTHDAY COLLECTION" },
      { name: "BIRTHDAY COLLECTION" },
      { name: "FRIENDSHIP DAY GIFTS" },
      { name: "CORPORATE GIFTS" },
      { name: "BACK TO SCHOOL GIFTS" },
      { name: "SYMPATHY PLANTS" },
      { name: "GIFTS FOR PARENTS" },
      { name: "HOUSEWARMING COLLECTION" },
      { name: "GRANDPARENTS DAY GIFTS" },
      { name: "THANK YOU COLLECTION" },
    ],
    PlantLifeStyles: [
      { name: "FENG SHUI PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "PLANTS FOR BEGINNERS" },
      { name: "AIR PURIFYING PLANTS" },
      { name: "ZODIAC PLANTS" },
    ],
    ProductImages: [
      { name: "Gymnocalycium_baldianum1.jpg" },
      { name: "Gymnocalycium_baldianum2.jpg" },
      { name: "Gymnocalycium_baldianum3.jpg" },
      { name: "Gymnocalycium_baldianum4.jpg" },
      { name: "Gymnocalycium_baldianum5.jpg" },
    ],
  },
  {
    name: "Pink rain lily",
    code: "A002",
    description: "plant Detail",
    imageUrl: "Pink_rain_lily.jpg",
    ProductSizes: [
      { name: "SMALL", price: 3 },
      { name: "MEDIUM", price: 5 },
      { name: "LARGE", price: 8 },
    ],
    ProductCares: [{ name: "ADVANCE" }, { name: "EASY" }, { name: "MODERATE" }],
    ProductLights: [
      { name: "DIRECT LIGHT" },
      { name: "INDIRECT LIGHT" },
      { name: "LOW LIGHT" },
    ],
    PlantTypes: [
      { name: "MEDICINE PLANTS" },
      { name: "SUCCULENTS PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FLOOR PLANTS" },
      { name: "BONSAI PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "HANGING PLANTS" },
      { name: "HOUSE PLANTS" },
      { name: "OUTDOOR PLANTS" },
      { name: "RARE PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "TROPICAL PLANTS" },
    ],
    PlantGifts: [
      { name: "BIRTHDAY COLLECTION" },
      { name: "BIRTHDAY COLLECTION" },
      { name: "FRIENDSHIP DAY GIFTS" },
      { name: "CORPORATE GIFTS" },
      { name: "BACK TO SCHOOL GIFTS" },
      { name: "SYMPATHY PLANTS" },
      { name: "GIFTS FOR PARENTS" },
      { name: "HOUSEWARMING COLLECTION" },
      { name: "GRANDPARENTS DAY GIFTS" },
      { name: "THANK YOU COLLECTION" },
    ],
    PlantLifeStyles: [
      { name: "FENG SHUI PLANTS" },
      { name: "FARM PLANTS" },
      { name: "FRUIT PLANTS" },
      { name: "FLOWERING PLANTS" },
      { name: "PLANTS FOR BEGINNERS" },
      { name: "AIR PURIFYING PLANTS" },
      { name: "ZODIAC PLANTS" },
    ],
    ProductImages: [
      { name: "Pink_rain_lily1.jpg" },
      { name: "Pink_rain_lily2.jpg" },
      { name: "Pink_rain_lily3.jpg" },
      { name: "Pink_rain_lily4.jpg" },
      { name: "Pink_rain_lily5.jpg" },
    ],
  },
];

module.exports = payload;
