/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomerReview: typeof import('./src/components/CustomerReview.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PlantCard: typeof import('./src/components/PlantCard.vue')['default']
    PlantTypeCard: typeof import('./src/components/PlantTypeCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopTrendingPlant: typeof import('./src/components/TopTrendingPlant.vue')['default']
  }
}
